import ICclose from "../assets/icons/ICclose.svg";
import ICdashboard from "../assets/icons/ICdashboard.svg";
import ICdashboard_ from "../assets/icons/ICdashboard_.svg";
import ICusers from "../assets/icons/ICusers.svg";
import ICusers_ from "../assets/icons/ICusers_.svg";
import ICvalidator from "../assets/icons/ICvalidator.svg";
import ICvalidator_ from "../assets/icons/ICvalidator_.svg";
import ICwithdraw from "../assets/icons/ICwithdraw.svg";
import ICwithdraw_ from "../assets/icons/ICwithdraw_.svg";
import ICgear from "../assets/icons/ICgear.svg";
import ICgear_ from "../assets/icons/ICgear_.svg";
import ICtrophy from "../assets/icons/ICtrophy.svg";
import ICtrophy_ from "../assets/icons/ICtrophy_.svg";
import ICcard from "../assets/icons/ICcard.svg";
import ICcard_ from "../assets/icons/ICcard_.svg";
import ICorders from "../assets/icons/ICorders.svg";
import ICorders_ from "../assets/icons/ICorders_.svg";
import ICcart from "../assets/icons/ICcart.svg";
import ICcart_ from "../assets/icons/ICcart_.svg";
import ICproducts from "../assets/icons/ICproducts.svg";
import ICproducts_ from "../assets/icons/ICproducts_.svg";
import ICinfo from "../assets/icons/ICinfo.svg";
import ICinfo_ from "../assets/icons/ICinfo_.svg";
import ICcategory from "../assets/icons/ICcategory.svg";
import ICcategory_ from "../assets/icons/ICcategory_.svg";
import ICbrand from "../assets/icons/ICbrand.svg";
import ICbrand_ from "../assets/icons/ICbrand_.svg";

import IClogout from "../assets/icons/IClogout.svg";
import IClogout1 from "../assets/icons/IClogout1.svg";
import ICdoller from "../assets/icons/ICdoller.svg";
import ICtxn from "../assets/icons/ICtxn.svg";
import ICusers1 from "../assets/icons/ICusers1.svg";
import ICpending from "../assets/icons/ICpending.svg";
import ICcalender from "../assets/icons/ICcalender.svg";
import IClens from "../assets/icons/IClens.svg";
import ICeye from "../assets/icons/ICeye.svg";
import ICeyeWhite from "../assets/icons/ICeyeWhite.svg";
import ICdone from "../assets/icons/ICdone.svg";
import ICcloseRed from "../assets/icons/ICcloseRed.svg";
import ICedit from "../assets/icons/ICedit.svg";
import ICsucces from "../assets/icons/ICsucces.svg";
import ICerror from "../assets/icons/ICerror.svg";
import ICusersWhite from "../assets/icons/ICusersWhite.svg";
import ICplus from "../assets/icons/ICplus.svg";
import ICusers2 from "../assets/icons/ICusers2.svg";
import ICservers from "../assets/icons/ICservers.svg";
import ICeye1 from "../assets/icons/ICeye1.svg";
import ICgraphUp from "../assets/icons/ICgraphUp.svg";
import ICgraphDown from "../assets/icons/ICgraphDown.svg";
import ICarrowDown from "../assets/icons/ICarrowDown.svg";

import BGlogin from "../assets/images/BGlogin.webp";
import BGlogin2 from "../assets/images/BGlogin2.webp";
import BGb from "../assets/images/BGb.svg";
import BGg from "../assets/images/BGg.svg";
import BGo from "../assets/images/BGo.svg";
import BGp from "../assets/images/BGp.svg";
import BGdb from "../assets/images/BGdb.svg";

import app from "../assets/logos/LOGOapp.svg";
import LOGOappfull from "../assets/logos/LOGOnetwork_.svg";

export class IC {
  static dashboard = ICdashboard;
  static dashboard_ = ICdashboard_;
  static users = ICusers;
  static users_ = ICusers_;
  static validator = ICvalidator;
  static validator_ = ICvalidator_;
  static withdraw = ICwithdraw;
  static withdraw_ = ICwithdraw_;
  static gear = ICgear;
  static gear_ = ICgear_;
  static trophy = ICtrophy;
  static trophy_ = ICtrophy_;
  static card = ICcard;
  static card_ = ICcard_;
  static orders = ICorders;
  static orders_ = ICorders_;
  static cart = ICcart;
  static cart_ = ICcart_;
  static products = ICproducts;
  static products_ = ICproducts_;
  static info = ICinfo;
  static info_ = ICinfo_;
  static category = ICcategory;
  static category_ = ICcategory_;
  static brand = ICbrand;
  static brand_ = ICbrand_;

  static close = ICclose;
  static logout = IClogout;
  static logout1 = IClogout1;

  static doller = ICdoller;
  static txn = ICtxn;
  static users1 = ICusers1;
  static pending = ICpending;
  static calender = ICcalender;
  static lens = IClens;
  static eye = ICeye;
  static eyeWhite = ICeyeWhite;
  static done = ICdone;
  static closeRed = ICcloseRed;
  static edit = ICedit;
  static succes = ICsucces;
  static error = ICerror;
  static usersWhite = ICusersWhite;
  static plus = ICplus;
  static users2 = ICusers2;
  static servers = ICservers;
  static eye1 = ICeye1;
  static graphUp = ICgraphUp;
  static graphDown = ICgraphDown;
  static arrowDown = ICarrowDown;
}

export class BG {
  static login = BGlogin;
  static login2 = BGlogin2;
  static b = BGb;
  static g = BGg;
  static o = BGo;
  static p = BGp;
  static db = BGdb;
}

export class Logo {
  static app = app;
  static appFull = LOGOappfull;
}
